// Comprehensive Strategy Tools Library
// 50+ tools across 10 categories for strategic decision intelligence

import type { Plan } from './users';

export type ToolCategory =
  | 'Diagnosis'
  | 'Growth'
  | 'Portfolio'
  | 'Scenarios'
  | 'Execution'
  | 'Risk'
  | 'Digital'
  | 'Governance'
  | 'Innovation'
  | 'Finance';

export type ToolComplexity = 'Intro' | 'Intermediate' | 'Advanced';

export interface StrategyToolFull {
  id: string;
  name: string;
  category: ToolCategory;
  description: string;
  longDescription: string;
  complexity: ToolComplexity;
  requiredPlan: Plan;
  estimatedTime: string;
  deliverable: string;
  bestFor: string[];
  keyQuestions: string[];
  relatedTools: string[];
  icon: string;
}

export const toolCategories: { id: ToolCategory; label: string; icon: string; description: string }[] = [
  { id: 'Diagnosis', label: 'Diagnosis & Discovery', icon: '🔍', description: 'Understand your current state and uncover hidden insights' },
  { id: 'Growth', label: 'Growth & Expansion', icon: '📈', description: 'Identify and capture growth opportunities' },
  { id: 'Portfolio', label: 'Portfolio Management', icon: '📊', description: 'Optimize resource allocation across initiatives' },
  { id: 'Scenarios', label: 'Scenario Planning', icon: '🎯', description: 'Model futures and test strategic options' },
  { id: 'Execution', label: 'Execution & Delivery', icon: '⚡', description: 'Turn strategy into action and results' },
  { id: 'Risk', label: 'Risk & Resilience', icon: '🛡️', description: 'Identify, assess, and mitigate strategic risks' },
  { id: 'Digital', label: 'Digital & Technology', icon: '💻', description: 'Drive digital transformation and tech strategy' },
  { id: 'Governance', label: 'Governance & Reporting', icon: '📋', description: 'Enable effective oversight and communication' },
  { id: 'Innovation', label: 'Innovation & R&D', icon: '🚀', description: 'Foster innovation and manage R&D portfolio' },
  { id: 'Finance', label: 'Financial Strategy', icon: '💰', description: 'Capital allocation and value creation' },
];

export const strategyToolsLibrary: StrategyToolFull[] = [
  // ============ DIAGNOSIS & DISCOVERY ============
  {
    id: 'tool-d1',
    name: 'Strategic Risk Radar',
    category: 'Diagnosis',
    description: 'Map and prioritize strategic risks across your organization',
    longDescription: 'A comprehensive risk mapping tool that helps identify, categorize, and prioritize strategic risks. Uses a radar visualization to show risk concentration, velocity, and interconnections across different business dimensions.',
    complexity: 'Intermediate',
    requiredPlan: 'Free',
    estimatedTime: '2-3 hours',
    deliverable: 'Risk radar map with prioritized risk clusters and mitigation recommendations',
    bestFor: ['CROs', 'CSOs', 'Board members', 'Risk committees'],
    keyQuestions: ['What are our top strategic risks?', 'How are risks interconnected?', 'Which risks are accelerating?'],
    relatedTools: ['tool-r1', 'tool-s2', 'tool-d3'],
    icon: '🎯',
  },
  {
    id: 'tool-d2',
    name: 'Signal Scanning Canvas',
    category: 'Diagnosis',
    description: 'Identify early warning signals and emerging trends',
    longDescription: 'Systematic approach to scanning the external environment for weak signals, emerging trends, and potential disruptions. Helps organizations build early warning capabilities and strategic foresight.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '3-4 hours',
    deliverable: 'Signal inventory with trend analysis and strategic implications',
    bestFor: ['Strategy teams', 'Innovation leads', 'Market intelligence'],
    keyQuestions: ['What signals are we missing?', 'Which trends will impact us?', 'How should we adapt?'],
    relatedTools: ['tool-s1', 'tool-g3', 'tool-i2'],
    icon: '📡',
  },
  {
    id: 'tool-d3',
    name: 'Strategic Health Check',
    category: 'Diagnosis',
    description: 'Assess organizational readiness for strategic initiatives',
    longDescription: 'A diagnostic assessment that evaluates organizational capabilities, culture, and readiness across multiple dimensions. Identifies strengths to leverage and gaps to address before launching major initiatives.',
    complexity: 'Intro',
    requiredPlan: 'Free',
    estimatedTime: '1-2 hours',
    deliverable: 'Health scorecard with capability gaps and improvement priorities',
    bestFor: ['CHROs', 'COOs', 'Transformation leads'],
    keyQuestions: ['Are we ready for this initiative?', 'What capabilities do we lack?', 'Where should we invest?'],
    relatedTools: ['tool-e1', 'tool-d4', 'tool-dg2'],
    icon: '🏥',
  },
  {
    id: 'tool-d4',
    name: 'Stakeholder Mapping',
    category: 'Diagnosis',
    description: 'Understand influence and alignment of key stakeholders',
    longDescription: 'Map stakeholder landscape including power, interest, influence, and current disposition. Essential for change management, M&A, and major transformation initiatives.',
    complexity: 'Intro',
    requiredPlan: 'Free',
    estimatedTime: '1 hour',
    deliverable: 'Stakeholder map with engagement strategy recommendations',
    bestFor: ['Project leads', 'Change managers', 'M&A teams'],
    keyQuestions: ['Who are the key stakeholders?', 'What are their interests?', 'How do we engage them?'],
    relatedTools: ['tool-d3', 'tool-gv1', 'tool-e3'],
    icon: '👥',
  },
  {
    id: 'tool-d5',
    name: 'Competitive Position Analyzer',
    category: 'Diagnosis',
    description: 'Benchmark your strategic position against competitors',
    longDescription: 'Deep analysis of competitive positioning across multiple dimensions including market share, capabilities, customer perception, and strategic moves. Identifies competitive gaps and opportunities.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '4-6 hours',
    deliverable: 'Competitive position matrix with strategic recommendations',
    bestFor: ['CSOs', 'Marketing leaders', 'Business unit heads'],
    keyQuestions: ['Where do we stand vs competitors?', 'What are our distinctive advantages?', 'Where are we vulnerable?'],
    relatedTools: ['tool-g1', 'tool-g3', 'tool-d2'],
    icon: '⚔️',
  },

  // ============ GROWTH & EXPANSION ============
  {
    id: 'tool-g1',
    name: 'Growth Opportunity Matrix',
    category: 'Growth',
    description: 'Identify and prioritize growth opportunities',
    longDescription: 'Structured framework for identifying, evaluating, and prioritizing growth opportunities across markets, products, and business models. Combines market attractiveness with organizational fit.',
    complexity: 'Intermediate',
    requiredPlan: 'Free',
    estimatedTime: '3-4 hours',
    deliverable: 'Prioritized growth opportunities with investment recommendations',
    bestFor: ['CEOs', 'CSOs', 'Business development leads'],
    keyQuestions: ['Where should we grow?', 'Which opportunities fit our capabilities?', 'What investment is required?'],
    relatedTools: ['tool-g2', 'tool-p1', 'tool-f2'],
    icon: '🎰',
  },
  {
    id: 'tool-g2',
    name: 'Innovation Pipeline Canvas',
    category: 'Growth',
    description: 'Structure and manage innovation initiatives',
    longDescription: 'Visual management tool for the innovation pipeline from ideation through commercialization. Tracks progress, resource allocation, and expected returns across innovation horizons.',
    complexity: 'Advanced',
    requiredPlan: 'Pro',
    estimatedTime: '2-3 hours',
    deliverable: 'Innovation pipeline view with stage-gate analysis',
    bestFor: ['CTOs', 'Innovation leads', 'R&D directors'],
    keyQuestions: ['What is in our pipeline?', 'Are we balanced across horizons?', 'What should we accelerate?'],
    relatedTools: ['tool-i1', 'tool-i3', 'tool-p2'],
    icon: '🚀',
  },
  {
    id: 'tool-g3',
    name: 'Market Entry Framework',
    category: 'Growth',
    description: 'Evaluate new market opportunities systematically',
    longDescription: 'Comprehensive framework for assessing new market opportunities including market sizing, competitive dynamics, entry barriers, and go-to-market strategy options.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '4-5 hours',
    deliverable: 'Market entry recommendation with execution roadmap',
    bestFor: ['CSOs', 'Regional heads', 'Business development'],
    keyQuestions: ['Is this market attractive?', 'Can we win here?', 'How should we enter?'],
    relatedTools: ['tool-g1', 'tool-d5', 'tool-s1'],
    icon: '🌍',
  },
  {
    id: 'tool-g4',
    name: 'Customer Value Proposition Designer',
    category: 'Growth',
    description: 'Design compelling value propositions for target segments',
    longDescription: 'Structured approach to designing and testing value propositions. Maps customer jobs, pains, and gains to product/service features, ensuring product-market fit.',
    complexity: 'Intro',
    requiredPlan: 'Free',
    estimatedTime: '2-3 hours',
    deliverable: 'Value proposition canvas with validation plan',
    bestFor: ['Product managers', 'Marketing leads', 'Founders'],
    keyQuestions: ['What do customers really value?', 'How do we differentiate?', 'Is our proposition compelling?'],
    relatedTools: ['tool-g1', 'tool-i2', 'tool-d5'],
    icon: '💎',
  },
  {
    id: 'tool-g5',
    name: 'M&A Target Screener',
    category: 'Growth',
    description: 'Identify and evaluate potential acquisition targets',
    longDescription: 'Systematic screening and evaluation of potential M&A targets based on strategic fit, financial attractiveness, and integration complexity.',
    complexity: 'Advanced',
    requiredPlan: 'Enterprise',
    estimatedTime: '6-8 hours',
    deliverable: 'Target shortlist with preliminary valuation ranges',
    bestFor: ['Corporate development', 'CSOs', 'CFOs'],
    keyQuestions: ['Who should we acquire?', 'What is strategic fit?', 'What would we pay?'],
    relatedTools: ['tool-g1', 'tool-f3', 'tool-d4'],
    icon: '🤝',
  },

  // ============ PORTFOLIO MANAGEMENT ============
  {
    id: 'tool-p1',
    name: 'Portfolio Health Matrix',
    category: 'Portfolio',
    description: 'Visualize initiative health across dimensions',
    longDescription: 'Multi-dimensional view of portfolio health showing strategic alignment, execution progress, resource utilization, and risk exposure for all initiatives.',
    complexity: 'Intermediate',
    requiredPlan: 'Free',
    estimatedTime: '2-3 hours',
    deliverable: 'Portfolio health dashboard with intervention recommendations',
    bestFor: ['PMO leads', 'CSOs', 'COOs'],
    keyQuestions: ['Which initiatives are at risk?', 'Where should we intervene?', 'Is the portfolio balanced?'],
    relatedTools: ['tool-p2', 'tool-e1', 'tool-r1'],
    icon: '📊',
  },
  {
    id: 'tool-p2',
    name: 'Resource Allocation Optimizer',
    category: 'Portfolio',
    description: 'Optimize resource distribution across initiatives',
    longDescription: 'Quantitative tool for optimizing resource allocation across the portfolio. Models trade-offs between initiatives and recommends optimal distribution based on strategic priorities.',
    complexity: 'Advanced',
    requiredPlan: 'Pro',
    estimatedTime: '3-4 hours',
    deliverable: 'Optimized resource allocation with sensitivity analysis',
    bestFor: ['CFOs', 'PMO leads', 'COOs'],
    keyQuestions: ['Are resources optimally allocated?', 'What are the trade-offs?', 'Where should we reallocate?'],
    relatedTools: ['tool-p1', 'tool-p3', 'tool-f1'],
    icon: '⚖️',
  },
  {
    id: 'tool-p3',
    name: 'Initiative Prioritization Grid',
    category: 'Portfolio',
    description: 'Score and rank initiatives by strategic value',
    longDescription: 'Structured scoring framework for evaluating and ranking initiatives based on strategic impact, feasibility, resource requirements, and risk. Enables objective prioritization decisions.',
    complexity: 'Intro',
    requiredPlan: 'Free',
    estimatedTime: '2 hours',
    deliverable: 'Ranked initiative list with scoring rationale',
    bestFor: ['Strategy teams', 'PMOs', 'Leadership teams'],
    keyQuestions: ['What should we prioritize?', 'What criteria matter most?', 'What should we defer?'],
    relatedTools: ['tool-p1', 'tool-e2', 'tool-d3'],
    icon: '📋',
  },
  {
    id: 'tool-p4',
    name: 'Portfolio Rebalancing Simulator',
    category: 'Portfolio',
    description: 'Model impact of portfolio changes before committing',
    longDescription: 'Simulation tool that models the impact of portfolio changes including adding, removing, or modifying initiatives. Shows projected outcomes under different allocation scenarios.',
    complexity: 'Advanced',
    requiredPlan: 'Enterprise',
    estimatedTime: '2-3 hours',
    deliverable: 'Rebalancing recommendations with projected impact',
    bestFor: ['CSOs', 'CFOs', 'PMO leads'],
    keyQuestions: ['What if we reallocate?', 'What are the projected outcomes?', 'What is optimal balance?'],
    relatedTools: ['tool-p2', 'tool-s1', 'tool-f1'],
    icon: '🔄',
  },
  {
    id: 'tool-p5',
    name: 'Initiative Dependency Mapper',
    category: 'Portfolio',
    description: 'Visualize and manage cross-initiative dependencies',
    longDescription: 'Maps dependencies between initiatives including resource, technology, and sequencing dependencies. Critical for understanding portfolio risk and execution planning.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '2-3 hours',
    deliverable: 'Dependency network with critical path analysis',
    bestFor: ['PMO leads', 'Project managers', 'COOs'],
    keyQuestions: ['What depends on what?', 'What is the critical path?', 'Where are the bottlenecks?'],
    relatedTools: ['tool-e2', 'tool-r2', 'tool-p1'],
    icon: '🔗',
  },

  // ============ SCENARIO PLANNING ============
  {
    id: 'tool-s1',
    name: 'Scenario Builder',
    category: 'Scenarios',
    description: 'Create and compare strategic scenarios',
    longDescription: 'Guided framework for building robust strategic scenarios based on key uncertainties and driving forces. Enables comparison of strategic options across different futures.',
    complexity: 'Intermediate',
    requiredPlan: 'Free',
    estimatedTime: '4-6 hours',
    deliverable: 'Scenario set with strategic implications and signposts',
    bestFor: ['Strategy teams', 'CSOs', 'Planning functions'],
    keyQuestions: ['What futures are possible?', 'How should we prepare?', 'What are the signposts?'],
    relatedTools: ['tool-s2', 'tool-s3', 'tool-d2'],
    icon: '🎭',
  },
  {
    id: 'tool-s2',
    name: 'Stress Test Simulator',
    category: 'Scenarios',
    description: 'Test strategy resilience under extreme conditions',
    longDescription: 'Stress testing tool that evaluates strategy performance under extreme but plausible scenarios. Identifies vulnerabilities and helps build strategic resilience.',
    complexity: 'Advanced',
    requiredPlan: 'Pro',
    estimatedTime: '3-4 hours',
    deliverable: 'Stress test results with resilience recommendations',
    bestFor: ['CROs', 'CFOs', 'Strategy teams'],
    keyQuestions: ['Can we survive this scenario?', 'What breaks first?', 'How do we build resilience?'],
    relatedTools: ['tool-r1', 'tool-r3', 'tool-s1'],
    icon: '💪',
  },
  {
    id: 'tool-s3',
    name: 'Decision Tree Mapper',
    category: 'Scenarios',
    description: 'Map decision paths and outcomes',
    longDescription: 'Visual tool for mapping decision trees with branching scenarios, probabilities, and expected outcomes. Supports complex strategic decisions with multiple contingencies.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '2-3 hours',
    deliverable: 'Decision tree with expected value analysis',
    bestFor: ['Executives', 'Strategy teams', 'M&A teams'],
    keyQuestions: ['What are our options?', 'What are the likely outcomes?', 'What is optimal path?'],
    relatedTools: ['tool-s1', 'tool-f2', 'tool-r1'],
    icon: '🌳',
  },
  {
    id: 'tool-s4',
    name: 'Wargaming Facilitator',
    category: 'Scenarios',
    description: 'Simulate competitive dynamics and strategic moves',
    longDescription: 'Structured approach to competitive wargaming that simulates market dynamics, competitor responses, and strategic interactions. Reveals blind spots and tests strategic assumptions.',
    complexity: 'Advanced',
    requiredPlan: 'Enterprise',
    estimatedTime: '6-8 hours',
    deliverable: 'Wargame insights with competitive strategy recommendations',
    bestFor: ['CSOs', 'Business unit heads', 'Strategy teams'],
    keyQuestions: ['How will competitors respond?', 'What are our blind spots?', 'How do we win?'],
    relatedTools: ['tool-d5', 'tool-s1', 'tool-g3'],
    icon: '♟️',
  },
  {
    id: 'tool-s5',
    name: 'Real Options Analyzer',
    category: 'Scenarios',
    description: 'Value strategic flexibility and optionality',
    longDescription: 'Quantitative framework for valuing strategic options including the right to expand, contract, defer, or abandon initiatives. Supports investment decisions under uncertainty.',
    complexity: 'Advanced',
    requiredPlan: 'Enterprise',
    estimatedTime: '4-5 hours',
    deliverable: 'Option valuation with decision recommendations',
    bestFor: ['CFOs', 'Corporate development', 'Strategy teams'],
    keyQuestions: ['What is the option worth?', 'When should we exercise?', 'How do we preserve optionality?'],
    relatedTools: ['tool-f2', 'tool-s3', 'tool-p4'],
    icon: '🎲',
  },

  // ============ EXECUTION & DELIVERY ============
  {
    id: 'tool-e1',
    name: 'OKR Tracker',
    category: 'Execution',
    description: 'Track objectives and key results',
    longDescription: 'Comprehensive OKR management tool that tracks progress, enables alignment, and facilitates regular check-ins. Connects team objectives to strategic priorities.',
    complexity: 'Intro',
    requiredPlan: 'Free',
    estimatedTime: '1-2 hours',
    deliverable: 'OKR dashboard with progress tracking',
    bestFor: ['All levels', 'Team leads', 'HR/People teams'],
    keyQuestions: ['Are we on track?', 'What needs attention?', 'How do OKRs align?'],
    relatedTools: ['tool-e2', 'tool-p1', 'tool-gv2'],
    icon: '🎯',
  },
  {
    id: 'tool-e2',
    name: 'Milestone Dashboard',
    category: 'Execution',
    description: 'Monitor progress against strategic milestones',
    longDescription: 'Executive dashboard tracking progress against key strategic milestones. Provides early warning of delays and enables proactive intervention.',
    complexity: 'Intro',
    requiredPlan: 'Free',
    estimatedTime: '1 hour',
    deliverable: 'Milestone status view with trend analysis',
    bestFor: ['PMO leads', 'Executives', 'Project sponsors'],
    keyQuestions: ['Are milestones on track?', 'What is at risk?', 'Where should we intervene?'],
    relatedTools: ['tool-e1', 'tool-p1', 'tool-e3'],
    icon: '🏁',
  },
  {
    id: 'tool-e3',
    name: 'Change Readiness Accelerator',
    category: 'Execution',
    description: 'Assess and accelerate change readiness',
    longDescription: 'Diagnostic and action planning tool for organizational change. Assesses readiness, identifies resistance points, and generates targeted interventions.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '3-4 hours',
    deliverable: 'Change readiness assessment with action plan',
    bestFor: ['Change leads', 'HR/People teams', 'Transformation PMOs'],
    keyQuestions: ['Is the organization ready?', 'Where is resistance?', 'What interventions are needed?'],
    relatedTools: ['tool-d3', 'tool-d4', 'tool-e4'],
    icon: '🚀',
  },
  {
    id: 'tool-e4',
    name: 'Execution Risk Monitor',
    category: 'Execution',
    description: 'Track and mitigate execution risks in real-time',
    longDescription: 'Real-time monitoring of execution risks across the initiative portfolio. Combines leading indicators with predictive analytics to enable proactive risk management.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '2 hours',
    deliverable: 'Risk monitoring dashboard with alerts',
    bestFor: ['PMO leads', 'CROs', 'Project managers'],
    keyQuestions: ['What risks are materializing?', 'What are leading indicators?', 'Where should we act?'],
    relatedTools: ['tool-r1', 'tool-p5', 'tool-e2'],
    icon: '👁️',
  },
  {
    id: 'tool-e5',
    name: 'Resource Conflict Resolver',
    category: 'Execution',
    description: 'Identify and resolve resource conflicts across initiatives',
    longDescription: 'Tool for identifying resource conflicts and bottlenecks across the portfolio. Provides recommendations for resolution including resequencing, substitution, or augmentation.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '2-3 hours',
    deliverable: 'Conflict analysis with resolution options',
    bestFor: ['PMO leads', 'Resource managers', 'COOs'],
    keyQuestions: ['Where are the conflicts?', 'What are the options?', 'How do we resolve?'],
    relatedTools: ['tool-p2', 'tool-p5', 'tool-e2'],
    icon: '🔧',
  },

  // ============ RISK & RESILIENCE ============
  {
    id: 'tool-r1',
    name: 'Risk Heatmap Generator',
    category: 'Risk',
    description: 'Visualize risk concentration areas',
    longDescription: 'Dynamic heatmap visualization of risk concentration across dimensions including impact, likelihood, velocity, and controllability. Enables intuitive risk communication.',
    complexity: 'Intermediate',
    requiredPlan: 'Free',
    estimatedTime: '2 hours',
    deliverable: 'Interactive risk heatmap with drill-down capability',
    bestFor: ['CROs', 'Audit committees', 'Risk teams'],
    keyQuestions: ['Where is risk concentrated?', 'What is most urgent?', 'How do risks compare?'],
    relatedTools: ['tool-d1', 'tool-r2', 'tool-r3'],
    icon: '🔥',
  },
  {
    id: 'tool-r2',
    name: 'Monte Carlo Simulator',
    category: 'Risk',
    description: 'Run probabilistic risk simulations',
    longDescription: 'Advanced simulation tool that runs thousands of scenarios to model outcome distributions. Quantifies uncertainty and provides probability-weighted forecasts.',
    complexity: 'Advanced',
    requiredPlan: 'Pro',
    estimatedTime: '3-4 hours',
    deliverable: 'Probability distributions with confidence intervals',
    bestFor: ['CFOs', 'CROs', 'Quantitative analysts'],
    keyQuestions: ['What is the range of outcomes?', 'What is the probability of success?', 'What drives variance?'],
    relatedTools: ['tool-s2', 'tool-f2', 'tool-r1'],
    icon: '🎰',
  },
  {
    id: 'tool-r3',
    name: 'Business Continuity Planner',
    category: 'Risk',
    description: 'Plan for operational resilience',
    longDescription: 'Framework for developing and testing business continuity plans. Identifies critical processes, dependencies, and recovery requirements.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '4-6 hours',
    deliverable: 'Business continuity plan with recovery procedures',
    bestFor: ['COOs', 'CROs', 'Operations leads'],
    keyQuestions: ['What is critical?', 'What are recovery requirements?', 'Are we prepared?'],
    relatedTools: ['tool-r1', 'tool-s2', 'tool-e4'],
    icon: '🛟',
  },
  {
    id: 'tool-r4',
    name: 'Emerging Risk Scanner',
    category: 'Risk',
    description: 'Identify and track emerging risks',
    longDescription: 'Systematic scanning for emerging risks that may not yet be on the radar. Combines external signals with internal indicators to provide early warning.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '2-3 hours',
    deliverable: 'Emerging risk inventory with monitoring plan',
    bestFor: ['CROs', 'Strategy teams', 'Board risk committees'],
    keyQuestions: ['What risks are emerging?', 'How do we monitor?', 'When do we act?'],
    relatedTools: ['tool-d2', 'tool-r1', 'tool-s1'],
    icon: '🔭',
  },
  {
    id: 'tool-r5',
    name: 'Risk Appetite Framework Builder',
    category: 'Risk',
    description: 'Define and operationalize risk appetite',
    longDescription: 'Guided process for defining organizational risk appetite and translating it into operational risk limits and tolerances.',
    complexity: 'Advanced',
    requiredPlan: 'Enterprise',
    estimatedTime: '6-8 hours',
    deliverable: 'Risk appetite statement with operational limits',
    bestFor: ['Boards', 'CROs', 'Audit committees'],
    keyQuestions: ['What risks will we accept?', 'What are our limits?', 'How do we enforce?'],
    relatedTools: ['tool-r1', 'tool-gv1', 'tool-gv3'],
    icon: '📏',
  },

  // ============ DIGITAL & TECHNOLOGY ============
  {
    id: 'tool-dg1',
    name: 'Digital Maturity Assessment',
    category: 'Digital',
    description: 'Evaluate digital capabilities and gaps',
    longDescription: 'Comprehensive assessment of digital maturity across technology, process, people, and culture dimensions. Benchmarks against industry peers and identifies priority gaps.',
    complexity: 'Intro',
    requiredPlan: 'Free',
    estimatedTime: '2-3 hours',
    deliverable: 'Digital maturity scorecard with improvement roadmap',
    bestFor: ['CTOs', 'CDOs', 'Digital transformation leads'],
    keyQuestions: ['How digitally mature are we?', 'Where are the gaps?', 'What should we prioritize?'],
    relatedTools: ['tool-dg2', 'tool-dg3', 'tool-d3'],
    icon: '📱',
  },
  {
    id: 'tool-dg2',
    name: 'Technology Roadmap Builder',
    category: 'Digital',
    description: 'Plan technology investments over time',
    longDescription: 'Strategic technology planning tool that maps current state, target architecture, and transition roadmap. Aligns technology investments with business strategy.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '4-6 hours',
    deliverable: 'Technology roadmap with investment timeline',
    bestFor: ['CTOs', 'Enterprise architects', 'IT leaders'],
    keyQuestions: ['What technology do we need?', 'When should we invest?', 'How do we transition?'],
    relatedTools: ['tool-dg1', 'tool-dg4', 'tool-f1'],
    icon: '🗺️',
  },
  {
    id: 'tool-dg3',
    name: 'AI Readiness Evaluator',
    category: 'Digital',
    description: 'Assess readiness for AI adoption',
    longDescription: 'Evaluation framework for AI readiness covering data, talent, infrastructure, governance, and use case maturity. Identifies prerequisites and quick wins.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '3-4 hours',
    deliverable: 'Technology readiness assessment with adoption roadmap',
    bestFor: ['CTOs', 'CDOs', 'Technology leads'],
    keyQuestions: ['Are we ready for advanced analytics?', 'What prerequisites are missing?', 'Where should we start?'],
    relatedTools: ['tool-dg1', 'tool-i1', 'tool-dg4'],
    icon: '⚙️',
  },
  {
    id: 'tool-dg4',
    name: 'Technical Debt Analyzer',
    category: 'Digital',
    description: 'Quantify and prioritize technical debt reduction',
    longDescription: 'Analysis tool for identifying, quantifying, and prioritizing technical debt. Calculates business impact and recommends remediation approach.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '3-4 hours',
    deliverable: 'Technical debt inventory with remediation plan',
    bestFor: ['CTOs', 'Engineering leads', 'Architects'],
    keyQuestions: ['What technical debt do we have?', 'What is the business impact?', 'How do we address it?'],
    relatedTools: ['tool-dg2', 'tool-r1', 'tool-p3'],
    icon: '🏚️',
  },
  {
    id: 'tool-dg5',
    name: 'Digital Operating Model Designer',
    category: 'Digital',
    description: 'Design target digital operating model',
    longDescription: 'Framework for designing the target digital operating model including organization structure, capabilities, processes, and governance.',
    complexity: 'Advanced',
    requiredPlan: 'Enterprise',
    estimatedTime: '6-8 hours',
    deliverable: 'Target operating model with transition plan',
    bestFor: ['CDOs', 'COOs', 'Transformation leads'],
    keyQuestions: ['What operating model do we need?', 'How do we organize?', 'What capabilities are required?'],
    relatedTools: ['tool-dg1', 'tool-e3', 'tool-d3'],
    icon: '🏗️',
  },

  // ============ GOVERNANCE & REPORTING ============
  {
    id: 'tool-gv1',
    name: 'Board Reporting Template',
    category: 'Governance',
    description: 'Structure executive communications',
    longDescription: 'Best-practice templates for board and executive communications. Ensures consistent, high-quality reporting that enables effective governance.',
    complexity: 'Intro',
    requiredPlan: 'Free',
    estimatedTime: '1-2 hours',
    deliverable: 'Board-ready report with key insights',
    bestFor: ['CSOs', 'CFOs', 'Company secretaries'],
    keyQuestions: ['What should we report?', 'How do we present?', 'What decisions are needed?'],
    relatedTools: ['tool-gv2', 'tool-gv3', 'tool-p1'],
    icon: '📊',
  },
  {
    id: 'tool-gv2',
    name: 'ESG Scorecard',
    category: 'Governance',
    description: 'Track ESG metrics and progress',
    longDescription: 'Comprehensive ESG tracking dashboard covering environmental, social, and governance metrics. Aligns with major reporting frameworks and enables stakeholder communication.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '3-4 hours',
    deliverable: 'ESG scorecard with trend analysis',
    bestFor: ['Sustainability leads', 'Investor relations', 'Board members'],
    keyQuestions: ['How are we performing on ESG?', 'What are the trends?', 'Where should we focus?'],
    relatedTools: ['tool-gv1', 'tool-gv3', 'tool-r1'],
    icon: '🌱',
  },
  {
    id: 'tool-gv3',
    name: 'Strategic Decision Log',
    category: 'Governance',
    description: 'Document and track strategic decisions',
    longDescription: 'Structured repository for strategic decisions including rationale, assumptions, owners, and review triggers. Enables organizational learning and accountability.',
    complexity: 'Intro',
    requiredPlan: 'Free',
    estimatedTime: '1 hour',
    deliverable: 'Decision log with review schedule',
    bestFor: ['Strategy teams', 'PMOs', 'Executives'],
    keyQuestions: ['What did we decide?', 'Why did we decide?', 'When should we review?'],
    relatedTools: ['tool-gv1', 'tool-e1', 'tool-p1'],
    icon: '📝',
  },
  {
    id: 'tool-gv4',
    name: 'Governance Health Check',
    category: 'Governance',
    description: 'Assess effectiveness of governance structures',
    longDescription: 'Diagnostic assessment of governance effectiveness covering board composition, committee structures, information flows, and decision rights.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '3-4 hours',
    deliverable: 'Governance assessment with improvement recommendations',
    bestFor: ['Company secretaries', 'Board chairs', 'Audit committees'],
    keyQuestions: ['Is governance effective?', 'What are the gaps?', 'How do we improve?'],
    relatedTools: ['tool-gv1', 'tool-d4', 'tool-r5'],
    icon: '🏛️',
  },
  {
    id: 'tool-gv5',
    name: 'Regulatory Compliance Tracker',
    category: 'Governance',
    description: 'Monitor regulatory requirements and compliance',
    longDescription: 'Tracking tool for regulatory requirements, compliance status, and upcoming changes. Ensures proactive compliance management.',
    complexity: 'Intermediate',
    requiredPlan: 'Enterprise',
    estimatedTime: '2-3 hours',
    deliverable: 'Compliance dashboard with gap analysis',
    bestFor: ['Compliance officers', 'Legal teams', 'CROs'],
    keyQuestions: ['Are we compliant?', 'What changes are coming?', 'What gaps exist?'],
    relatedTools: ['tool-r1', 'tool-gv2', 'tool-gv4'],
    icon: '⚖️',
  },

  // ============ INNOVATION & R&D ============
  {
    id: 'tool-i1',
    name: 'Innovation Portfolio Balancer',
    category: 'Innovation',
    description: 'Balance innovation investments across horizons',
    longDescription: 'Framework for balancing innovation portfolio across the three horizons: core, adjacent, and transformational. Ensures sustainable innovation investment.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '2-3 hours',
    deliverable: 'Innovation portfolio view with balance recommendations',
    bestFor: ['CTOs', 'Innovation leads', 'CSOs'],
    keyQuestions: ['Is our portfolio balanced?', 'Are we investing enough in H3?', 'What should we adjust?'],
    relatedTools: ['tool-g2', 'tool-i3', 'tool-p1'],
    icon: '⚖️',
  },
  {
    id: 'tool-i2',
    name: 'Experiment Design Canvas',
    category: 'Innovation',
    description: 'Design and structure strategic experiments',
    longDescription: 'Framework for designing strategic experiments with clear hypotheses, success criteria, and learning objectives. Enables disciplined experimentation.',
    complexity: 'Intro',
    requiredPlan: 'Free',
    estimatedTime: '1-2 hours',
    deliverable: 'Experiment design with success criteria',
    bestFor: ['Product managers', 'Innovation teams', 'Business development'],
    keyQuestions: ['What are we testing?', 'How will we know if it works?', 'What will we learn?'],
    relatedTools: ['tool-g4', 'tool-i1', 'tool-s3'],
    icon: '🧪',
  },
  {
    id: 'tool-i3',
    name: 'R&D Portfolio Optimizer',
    category: 'Innovation',
    description: 'Optimize R&D investment allocation',
    longDescription: 'Quantitative optimization of R&D portfolio considering strategic value, probability of success, time to value, and resource requirements.',
    complexity: 'Advanced',
    requiredPlan: 'Enterprise',
    estimatedTime: '4-5 hours',
    deliverable: 'Optimized R&D portfolio with investment recommendations',
    bestFor: ['R&D directors', 'CTOs', 'CFOs'],
    keyQuestions: ['Is R&D optimally allocated?', 'What projects should we prioritize?', 'Where should we invest more?'],
    relatedTools: ['tool-i1', 'tool-p2', 'tool-f2'],
    icon: '🔬',
  },
  {
    id: 'tool-i4',
    name: 'IP Strategy Framework',
    category: 'Innovation',
    description: 'Develop and manage intellectual property strategy',
    longDescription: 'Framework for developing IP strategy including patent strategy, trade secret management, and IP monetization options.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '3-4 hours',
    deliverable: 'IP strategy document with action plan',
    bestFor: ['Legal teams', 'CTOs', 'R&D directors'],
    keyQuestions: ['What IP should we protect?', 'How do we monetize IP?', 'What are the risks?'],
    relatedTools: ['tool-i1', 'tool-g5', 'tool-r1'],
    icon: '📜',
  },
  {
    id: 'tool-i5',
    name: 'Open Innovation Connector',
    category: 'Innovation',
    description: 'Structure external innovation partnerships',
    longDescription: 'Framework for identifying, evaluating, and structuring external innovation partnerships including startups, academia, and ecosystem players.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '2-3 hours',
    deliverable: 'Partnership strategy with target list',
    bestFor: ['Innovation leads', 'Corporate development', 'CTOs'],
    keyQuestions: ['Who should we partner with?', 'What model should we use?', 'How do we structure?'],
    relatedTools: ['tool-g5', 'tool-i1', 'tool-d4'],
    icon: '🤝',
  },

  // ============ FINANCIAL STRATEGY ============
  {
    id: 'tool-f1',
    name: 'Capital Allocation Framework',
    category: 'Finance',
    description: 'Structure capital allocation decisions',
    longDescription: 'Framework for making and communicating capital allocation decisions across organic growth, M&A, dividends, and share repurchases.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '3-4 hours',
    deliverable: 'Capital allocation plan with decision criteria',
    bestFor: ['CFOs', 'CEOs', 'Boards'],
    keyQuestions: ['How should we allocate capital?', 'What are the trade-offs?', 'How do we communicate?'],
    relatedTools: ['tool-p2', 'tool-f2', 'tool-gv1'],
    icon: '💵',
  },
  {
    id: 'tool-f2',
    name: 'Investment Business Case Builder',
    category: 'Finance',
    description: 'Build compelling investment business cases',
    longDescription: 'Structured template for building investment business cases with financial projections, risk analysis, and sensitivity testing.',
    complexity: 'Intermediate',
    requiredPlan: 'Free',
    estimatedTime: '3-4 hours',
    deliverable: 'Investment business case with financial model',
    bestFor: ['Project sponsors', 'Finance teams', 'Business unit heads'],
    keyQuestions: ['Is this investment worthwhile?', 'What are the returns?', 'What are the risks?'],
    relatedTools: ['tool-f1', 'tool-r2', 'tool-p3'],
    icon: '📈',
  },
  {
    id: 'tool-f3',
    name: 'Valuation Multiples Analyzer',
    category: 'Finance',
    description: 'Analyze valuation multiples and comparables',
    longDescription: 'Analysis tool for understanding valuation multiples, comparable companies, and value drivers. Supports M&A and strategic planning.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '2-3 hours',
    deliverable: 'Valuation analysis with comparable benchmarks',
    bestFor: ['CFOs', 'Corporate development', 'Investor relations'],
    keyQuestions: ['What is our valuation?', 'How do we compare?', 'What drives value?'],
    relatedTools: ['tool-g5', 'tool-f1', 'tool-d5'],
    icon: '📊',
  },
  {
    id: 'tool-f4',
    name: 'Cost Optimization Scanner',
    category: 'Finance',
    description: 'Identify cost optimization opportunities',
    longDescription: 'Systematic approach to identifying cost optimization opportunities across the organization without compromising strategic capabilities.',
    complexity: 'Intermediate',
    requiredPlan: 'Pro',
    estimatedTime: '4-5 hours',
    deliverable: 'Cost optimization opportunities with implementation plan',
    bestFor: ['CFOs', 'COOs', 'Business unit heads'],
    keyQuestions: ['Where can we optimize costs?', 'What is the impact?', 'How do we implement?'],
    relatedTools: ['tool-p2', 'tool-e5', 'tool-f1'],
    icon: '✂️',
  },
  {
    id: 'tool-f5',
    name: 'Value Creation Bridge',
    category: 'Finance',
    description: 'Map sources of value creation',
    longDescription: 'Framework for mapping and quantifying sources of value creation from strategic initiatives. Connects strategy to shareholder value.',
    complexity: 'Advanced',
    requiredPlan: 'Enterprise',
    estimatedTime: '4-5 hours',
    deliverable: 'Value creation waterfall with initiative attribution',
    bestFor: ['CFOs', 'CSOs', 'Investor relations'],
    keyQuestions: ['Where is value created?', 'Which initiatives drive value?', 'How do we communicate?'],
    relatedTools: ['tool-f1', 'tool-f3', 'tool-gv1'],
    icon: '🌉',
  },
];

// Helper functions
export function getToolsByCategory(category: ToolCategory): StrategyToolFull[] {
  return strategyToolsLibrary.filter(tool => tool.category === category);
}

export function getToolsByPlan(plan: Plan): StrategyToolFull[] {
  const planHierarchy: Record<Plan, Plan[]> = {
    'Free': ['Free'],
    'Starter': ['Free', 'Starter'],
    'Pro': ['Free', 'Starter', 'Pro'],
    'Enterprise': ['Free', 'Starter', 'Pro', 'Enterprise'],
  };
  const allowedPlans = planHierarchy[plan];
  return strategyToolsLibrary.filter(tool => allowedPlans.includes(tool.requiredPlan));
}

export function getToolById(id: string): StrategyToolFull | undefined {
  return strategyToolsLibrary.find(tool => tool.id === id);
}

export function searchTools(query: string): StrategyToolFull[] {
  const lowerQuery = query.toLowerCase();
  return strategyToolsLibrary.filter(tool =>
    tool.name.toLowerCase().includes(lowerQuery) ||
    tool.description.toLowerCase().includes(lowerQuery) ||
    tool.category.toLowerCase().includes(lowerQuery) ||
    tool.bestFor.some(role => role.toLowerCase().includes(lowerQuery))
  );
}

export function getRelatedTools(toolId: string): StrategyToolFull[] {
  const tool = getToolById(toolId);
  if (!tool) return [];
  return tool.relatedTools
    .map(id => getToolById(id))
    .filter((t): t is StrategyToolFull => t !== undefined);
}

export const complexityColors: Record<ToolComplexity, string> = {
  'Intro': 'bg-green-500/20 text-green-400 border-green-500/30',
  'Intermediate': 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
  'Advanced': 'bg-red-500/20 text-red-400 border-red-500/30',
};

export const planColors: Record<Plan, string> = {
  'Free': 'bg-slate-500/20 text-slate-300 border-slate-500/30',
  'Starter': 'bg-blue-500/20 text-blue-400 border-blue-500/30',
  'Pro': 'bg-teal-500/20 text-teal-400 border-teal-500/30',
  'Enterprise': 'bg-purple-500/20 text-purple-400 border-purple-500/30',
};
